maintainer       "Heavy Water Operations, LLC"
maintainer_email "support@hw-ops.com"
license          "Apache 2.0"
description      "Installs/Configures the discovery library"
version          "0.2.0"
